version: '3.8'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: ${POSTGRES_DB}
    secrets:
      - postgres_password
    labels:
      - "traefik.enable=true"  # Enable Traefik for this container
      - "traefik.http.routers.timescaledb.rule=Host(`timescaledb.staklimriau.web.id`)"  # Replace with your public IP or domain
      - "traefik.http.routers.timescaledb.entrypoints=https"  # Use the HTTPS entry point
      - "traefik.http.routers.timescaledb.tls.certresolver=cloudflare"  # Use Let's Encrypt to get an SSL cert
      - "traefik.http.services.timescaledb.loadbalancer.server.port=5432"  # Internal PostgreSQL port
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    networks:
      - shared_network

volumes:
  timescaledb_data:

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt

networks:
  shared_network:
    external: true
