version: '3.8'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: ${POSTGRES_DB}
    secrets:
      - postgres_password
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    networks:
      - shared_network

volumes:
  timescaledb_data:

secrets:
  postgres_password:
    file: ./secrets/timescaledb_password.txt

networks:
  shared_network:
    external: true
