version: "3.8"

services:
  nodered:
    image: nodered/node-red:3.1
    container_name: nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    environment:
      - FLOWS=${FLOWS_FILE}
      # Optional: Use hashed password for admin auth
      - NODE_RED_ADMIN_PASSWORD_FILE:/run/secrets/nodered_password
    volumes:
      - nodered_data:/data
    secrets:
      - nodered_password
    networks:
      - shared_network

volumes:
  nodered_data:

secrets:
  nodered_password:
    file: ./secrets/nodered_password.txt

networks:
  shared_network:
    external: true
