version: "3.8"

services:
  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    environment:
      - FLOWS=${FLOWS_FILE}
      # Optional: Use hashed password for admin auth
      - NODE_RED_CREDENTIAL_SECRET= /run/secrets/nodered_password
    volumes:
      - nodered_data:/data
    secrets:
      - nodered_password
    labels:
      - "traefik.enable=true"  # Enable Traefik for this container
      - "traefik.http.routers.nodered.rule=Host(`nodered.staklimriau.web.id`)"  # Replace with your public IP or domain
      - "traefik.http.routers.nodered.entrypoints=https"  # Use the HTTPS entry point
      - "traefik.http.routers.nodered.tls.certresolver=cloudflare"  # Use Let's Encrypt to get an SSL cert
      - "traefik.http.services.nodered.loadbalancer.server.port=1880"  # Internal Node-RED port
    networks:
      - shared_network

volumes:
  nodered_data:

secrets:
  nodered_password:
    file: ./secrets/nodered_password.txt

networks:
  shared_network:
    external: true
