  # pgAdmin for PostgreSQL management
version: "3.8"

services:  
  pgadmin:
    image: dpage/pgadmin4
    container_name: db_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}  # Change this!
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password  # Change this!
    ports:
      - "8083:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    secrets:
      - pgadmin_password
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  pgadmin_data:

secrets:
  pgadmin_password:
    file: ./secrets/pgadmin_password.txt

