erDiagram
    aaws {
        station_id        TEXT         PK  "ID Stasiun"
        timestamp         TIMESTAMPTZ  PK  "Waktu Lengkap"
        model             TEXT             "Model Alat"
        serial_no         TEXT             "Nomor Seri"
        os_version        TEXT             "Versi OS"
        station_name      TEXT             "Nama Stasiun"
        date              DATE             "Tanggal"
        time              TIME             "Waktu"
        ws_meas_avg       TEXT             "WS Rata-rata"
        ws_max            TEXT             "WS Maksimum"
        wd_meas_avg       TEXT             "WD Rata-rata"
        ta_meas_avg       TEXT             "Suhu Rata-rata"
        ta_max            TEXT             "Suhu Maks"
        ta_min            TEXT             "Suhu Min"
        rh_meas_avg       TEXT             "Kelembapan Rata-rata"
        pa_meas_avg       TEXT             "Tekanan Udara"
        pr_meas_total     TEXT             "Curah Hujan Total"
        sr_meas_avg       TEXT             "Radiasi Surya Rata-rata"
        sr_max            TEXT             "Radiasi Surya Maks"
        batt_volt         TEXT             "Tegangan Baterai"
        ptemp_avg         TEXT             "Suhu Panel"
        lithium_battery   TEXT             "Status Baterai Lithium"
    }