version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9443:9443"
      - "9000:9000" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - shared_network
    # Uncomment below if you want to use secrets for any future config
    # secrets:
    #   - admin_password


volumes:
  portainer_data:

networks:
  shared_network:
    external: true

# Optional secrets block (not needed for Portainer itself, but good to practice)
# secrets:
#   admin_password:
#     file: ./secrets/admin_password.txt
