http:
  routers:
    soil-router:
      rule: Host(`soil.staklimriau.web.id`)
      entryPoints:
        - https
      service: soil-service
      tls:
        certResolver: cloudflare
  services:
    soil-service:
      loadBalancer:
        servers:
          - url: "http://192.168.12.189:8002"   # soil moisture via XAMPP/whatever
